### ISSUE TITLE
Developer Application

### ISSUE THREAD

**Issue by SkepCode** [Hyperfire-Dev/Dev-Application#2]
# Discord Username
Skeppy#5781

# Discord ID
887519628992073729

# What level are you in our server? (!rank)
over 5

# Do you have any active manual warns?
- [x] Yes
- [ ] No

# Do you have any past experience with coding in JS and Discord.js?
no

# Please provide us with your past experience along with references (if any).
no

# Anything else we should know?
no @HyperfireRS

**Comment by HyperfireRS** [comment]
Denied, you do not meet the requirements.
